In [1]:
import pandas as pd
import seaborn as sb

mass_shootings = pd.read_csv('assets/mass_shoot_data.csv')
mass_shootings.head(10)

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,2445939,"October 25, 2022",North Carolina,Greensboro,900 block of Circle Dr,2,4,NaN
1,2443879,"October 24, 2022",Missouri,Saint Louis,3125 S Kingshighway Blvd,3,4,NaN
2,2443849,"October 24, 2022",Illinois,Chicago,3200 block of W 30th St,1,3,NaN
3,2443627,"October 23, 2022",Texas,Brownsville,1200 block of W Saint Francis St,0,5,NaN
4,2443194,"October 23, 2022",Illinois,Chicago,4300 block of S Kedzie Ave,3,2,NaN
5,2443276,"October 23, 2022",Wisconsin,Milwaukee,N 34th St and W Wright St,0,4,NaN
6,2442695,"October 22, 2022",Wisconsin,Milwaukee,W Fond Du Lac and W Hoyt Pl,0,6,NaN
7,2443257,"October 22, 2022",North Carolina,Oxford,100 block of Granville St,0,6,NaN
8,2443231,"October 22, 2022",Arizona,Phoenix,6330 W Miami St,1,7,NaN
9,2443287,"October 22, 2022",Georgia,Cordele,1309 16th Ave E,0,4,NaN